name: nutri_balance
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

#================ DEPENDENCIES ================#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  http: ^1.2.1
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3
  pinput: ^5.0.2
  fl_chart: ^0.68.0
  get: ^4.6.6
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  month_picker_dialog: ^6.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_nutribalance.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/